INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('pain', 'Pain', 50, 0, 1),
	('eau', 'Eau', 50, 0, 1),
	('chocolat', 'Carré de chocolat'; 50, 0, 1),
	('saucisson', 'Saucisson sec', 50, 0, 1),
	('sandwich', 'Sandwich', 50, 0, 1),
	('pizza', 'Pizza', 50, 0, 1),
	('hamburger', 'Hamburger', 50, 0, 1),
	('chips', 'Paquet de chips', 50, 0, 1),
	('bolcacahuetes', 'Sachet de cachuètes', 50, 0, 1),
	('bolchips', 'Bol de chips', 50, 0, 1),
	('bolnoixcajou', 'Bol de Noix de cajoux', 50, 0, 1),
	('bolpistache', 'Bol de Pistache', 50, 0, 1),
	('mixapero', 'Mix apéro', 50, 0, 1),
	('fanta', 'Fanta', 50, 0, 1),
	('coca', 'Coca', 50, 0, 1),
	('oasis', 'Oasis', 50, 0, 1),
	('orangina', 'Orangina', 50, 0, 1),
	('sprite', 'Sprite', 50, 0, 1),
	('icetea', 'IceTea', 50, 0, 1),
	('drpepper', 'DrPepper', 50, 0, 1),
	('energy', 'Monster', 50, 0, 1),
	('jusfruit', 'Jus de Fruit', 50, 0, 1),
	('limonade', 'Limonade', 50, 0, 1),
	('coffee', 'Café', 50, 0, 1),
	('capuccino', 'Capuccino', 50, 0, 1),
	('tea', 'Thé', 50, 0, 1),
	('chicken_burger', 'Chicken Burger', 50, 0, 1),
	('fish_burger', 'Fish Burger', 50, 0, 1),
	('veggie_burger', 'Burger Veggie', 50, 0, 1),
	('bacon_burger', 'Bacon Burger', 50, 0, 1),
	('steakhouse_burger', 'Steakhouse', 50, 0, 1),
	('terminator_burger', 'Terminator', 50, 0, 1),
	('tacos', 'Tacos', 50, 0, 1),
	('chicken_wrap', 'Wrap au Poulet', 50, 0, 1),
	('fish_wrap', 'Wrap au Poisson', 50, 0, 1),
	('batonnets_de_mozzarella', 'Sticks Moza', 50, 0, 1),
	('oignon_rings', 'Oignon Rings', 50, 0, 1),
	('fries', 'Frites', 50, 0, 1),
	('salade', 'Salade', 50, 0, 1),
	('salade_cesar', 'Salade César', 50, 0, 1),
	('cupcake', 'Cupcake', 50, 0, 1),
	('milkshake', 'Milkshake', 50, 0, 1),
	('cheesecake', 'Cheesecake', 50, 0, 1),
	('smoothie', 'Smoothie', 50, 0, 1),
	('sundae', 'Sundae', 50, 0, 1),
	('churros', 'Churros', 50, 0, 1),
	('donuts', 'Donuts', 50, 0, 1),
	('brownie', 'Brownie', 50, 0, 1),
	('cookie', 'Cookie', 50, 0, 1)
;